title: "Yaoxin Li (Tom)"
author: "Yaoxin Li (Tom)"
description: "Aspiring Software Engineer with a passion for leveraging my technical, collaboration and design skills to drive deliverables and make an impact. Experienced with various technologies building high performance systems including PyTorch, AWS and more. "
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: Resume/CV}
  - {file: "README.md", title: Contact}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "tomli980411@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/HelloBearLYX"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/hblyx"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
